### ISSUE TITLE
Allow servers to be managed

### ISSUE THREAD

**Issue by acelaya** [shlinkio/shlink-dashboard#100]
Add a section for a servers CRUD. It should take into consideration the logged-in user.

Admins should also be able to attach servers they have created to managed users. To be defined if this is done from the users list, from the servers list, or both.

Any user who's not a managed user can create servers of their own.

 ---

### Todo
- [x] List own servers
- [x] Create own servers 
- [x] Delete server
- [x] Edit server 
- [ ] For admins 
    - [ ] Show other users with access to the server 
    - [ ] Attach/detach users from the server 

### Future
- When deleting, editing or detaching users from a server, take into consideration users actively using it.
- Export and import servers
